spring:
  application:
    name: Chat-Service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ChatDb

server:
  port: 8050

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/